# Generated by Django 4.1 on 2022-09-02 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='day',
            old_name='friday',
            new_name='day_of_week',
        ),
        migrations.RemoveField(
            model_name='day',
            name='monday',
        ),
        migrations.RemoveField(
            model_name='day',
            name='saturday',
        ),
        migrations.RemoveField(
            model_name='day',
            name='sunday',
        ),
        migrations.RemoveField(
            model_name='day',
            name='thursday',
        ),
        migrations.RemoveField(
            model_name='day',
            name='tuesday',
        ),
        migrations.RemoveField(
            model_name='day',
            name='wednesday',
        ),
    ]
