# Generated by Django 4.1 on 2022-09-02 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_rename_friday_day_day_of_week_remove_day_monday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='day_of_week',
            field=models.DateField(max_length=50),
        ),
    ]
