# Generated by Django 4.1 on 2022-09-02 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0003_alter_day_day_of_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='workout.day'),
        ),
    ]
